name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:

    - name: Install LocalTunnel
      run: |
          npm install -g localtunnel

    - name: Start LocalTunnel
      run: |
          ssh -R 5900:localhost:5900 serveo.net
          
    - name: Log In Details To VNC Server
      run: |
          chmod +x login.sh
          bash login.sh

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
