name: MacRDP
on: 
  workflow_dispatch:
  
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
    - name: Setup VNC Server
      run: |
          curl -s -o setup.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/setup.sh"
          chmod +x setup.sh
          bash setup.sh
      
    - name: Log In Details To VNC Server
      run: |
         chmod +x login.sh
         bash login.sh
      
    - name: Enable TCP Access
      run: |
         sudo pfctl -f /etc/pf.conf
         sudo pfctl -e
         sudo ifconfig en0 up

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2

