name: MacRDP
on: 
  workflow_dispatch:
  
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
  
      
    - name: Enable TCP Access
      run: |
         sudo pfctl -f /etc/pf.conf
         sudo pfctl -e
         sudo ifconfig en0 up

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2

