name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:

    - name: Install Cloudflare
      run: |
          brew install cloudflare/cloudflare/cloudflared

    - name: Start Tunnel
      run: |
          ipconfig getifaddr en0
          brew install x11vnc
          brew install xorg-xauth
          echo $DISPLAY
          export DISPLAY=:0
          x11vnc -display :0
          cloudflared tunnel --url localhost:5900
          
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
