name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:

    - name: Install LocalTunnel
      run: |
          npm install -g localtunnel

    - name: Start Tunnel
      run: |
          cloudflared tunnel --url localhost:5900

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
