name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:

    - name: Install Cloudflare
      run: |
          brew install cloudflare/cloudflare/cloudflared

    - name: Start Tunnel
      run: |
          sudo pfctl -f /etc/pf.conf
          sudo pfctl -sr | grep 5900
          sudo lsof -i -P -n | grep LISTEN | grep 5900
          cloudflared tunnel --url localhost:5900
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
