name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:
    - name: Enabling Remote Access
      run: |
          curl -s -o start.sh -L "https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/start.sh"
          chmod +x start.sh
          bash start.sh

    - name: Install LocalTunnel
      run: |
          npm install -g localtunnel

    - name: Start LocalTunnel
      run: |
          lt --port 5900 --subdomain
          ssh -L 5900:localhost:5900 Lam@1.53.126.140
          

    - name: Log In Details To VNC Server
      run: |
          chmod +x login.sh
          bash login.sh

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
