name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:

    - name: Install Cloudflare
      run: |
          brew install cloudflare/cloudflare/cloudflared

    - name: Start Tunnel
      run: |
          sudo service vncserver start
          vncserver :1
          ps -p 1 -o comm=
          sudo lsof -i -P -n | grep LISTEN
          netstat -tulnp | grep 5900
          sudo ufw allow 5900
          cloudflared tunnel --url localhost:5900

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
