name: MacRDP
on:
  workflow_dispatch:
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest

    steps:

    - name: Install Cloudflare
      run: |
          brew install cloudflare/cloudflare/cloudflared

    - name: Start Tunnel
      run: |
          ipconfig getifaddr en0
          curl -O https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-7.13.1-MacOSX-universal.pkg?lai_vid=NX12E0WwMcv8v&lai_sr=15-19&lai_sl=l&lai_p=1
          cloudflared tunnel --url localhost:5900
          
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
