name: MacRDP
on: 
  workflow_dispatch:
  
jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:                 
  
      
    - name: Enable TCP Access
      run: |
         sudo pfctl -f /etc/pf.conf
         sudo pfctl -e
         ifconfig -a
         ping -c 4 8.8.8.8
         sudo ifconfig en0 down
         sudo ifconfig en0 up
         sudo ipconfig set en0 DHCP
         ifconfig en0
         netstat -nr | grep default
         sudo route add default 192.168.64.1
         ping google.com
         sudo networksetup -setdnsservers Wi-Fi 8.8.8.8
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2

